# Generated by Django 5.1.6 on 2025-03-26 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('levels', models.CharField(choices=[('A1-C1', 'A1-C1'), ('A1-B1', 'A1-B1'), ('A2-C1', 'A2-C1'), ('B1-C2', 'B1-C2'), ('A1', 'A1')], default='A1', max_length=100)),
                ('lessons', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='A1', max_length=50)),
                ('num_part', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('full_textkey', models.TextField(blank=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='dolphin.section')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='dolphin.topic')),
            ],
        ),
        migrations.CreateModel(
            name='AudioExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioSrc', models.URLField()),
                ('correct_text', models.TextField()),
                ('position', models.PositiveIntegerField(default=1)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='dolphin.subtopic')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='dolphin.topic'),
        ),
    ]
