# Generated by Django 5.1.7 on 2025-05-27 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolphin.audioexercise')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listened_audios', to='dolphin.userprogress')),
            ],
            options={
                'unique_together': {('progress', 'audio')},
            },
        ),
    ]
