# Generated by Django 5.1.6 on 2025-03-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioexercise',
            name='audio_file',
            field=models.URLField(),
        ),
    ]
