# Generated by Django 5.1.6 on 2025-03-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0002_alter_audioexercise_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioexercise',
            old_name='audio_file',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='subtopic',
            old_name='vocab_level',
            new_name='level',
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='levels',
            field=models.CharField(choices=[('A1-C1', 'A1-C1'), ('A1-B1', 'A1-B1'), ('A2-C1', 'A2-C1'), ('B1-C2', 'B1-C2'), ('A1', 'A1')], default='A1', max_length=100),
        ),
        migrations.AlterField(
            model_name='audioexercise',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
