# Generated by Django 5.1.7 on 2025-04-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0002_remove_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
