# Generated by Django 5.1.6 on 2025-03-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0003_rename_audio_file_audioexercise_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='num_part',
            field=models.IntegerField(default=0),
        ),
    ]
