# Generated by Django 5.1.7 on 2025-04-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='nickname',
        ),
    ]
