# Generated by Django 5.1.7 on 2025-04-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0005_rename_username_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
