# Generated by Django 5.1.7 on 2025-04-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0007_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='audio_listened_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
