# Generated by Django 5.1.7 on 2025-04-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0008_userprogress_audio_listened_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='audio_listened_count',
        ),
    ]
