# Generated by Django 5.2 on 2025-04-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dolphin", "0010_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="active_seconds",
            new_name="active_time",
        ),
    ]
